# Generated by Django 3.2.21 on 2023-12-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../profile_ags3s0', upload_to='images/'),
        ),
    ]
